// Casino offers data
export const offersData = [
  {
    id: 1,
    name: 'Ignibet',
    badge: 'HOT',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop',
    bonusTitle: '665% Bonus & 750 FS up to €6250',
    minDeposit: '20€',
    bonusValue: '665%',
    freeSpins: 'Up to 750',
    cashback: '30%',
    withdrawTime: 'Up to 48h',
    license: 'Curaçao',
    terms: '+18 | T&C APPLY',
    description: '• There MAY be a promotion of €10 free or another promotion on our Discord. Open a ticket to check if the promotion is active.\n\n• 24/7 Live Support (for help with free spins)',
    link: 'https://example.com/ignibet'
  },
  {
    id: 2,
    name: 'Betify',
    badge: 'HOT',
    image: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?w=400&h=300&fit=crop',
    bonusTitle: 'Special GODMOTA VIP Program',
    minDeposit: '20€',
    bonusValue: '100%',
    freeSpins: 'Up to 100',
    cashback: '20%',
    withdrawTime: 'Up to 48h',
    license: 'Curaçao',
    terms: '+18 | T&C APPLY',
    description: '• There MAY be a promotion of €10 free or another promotion on our Discord. Open a ticket to check if the promotion is active.\n\n• 24/7 Live Support (for help with free spins)',
    link: 'https://example.com/betify'
  },
  {
    id: 3,
    name: 'Lollyspins',
    badge: 'NEW',
    image: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=400&h=300&fit=crop',
    bonusTitle: '400% Bonus up to €2200 & 350FS',
    minDeposit: '25€',
    bonusValue: '400%',
    freeSpins: 'Up to 350',
    cashback: '35%',
    withdrawTime: 'Up to 48h',
    license: 'Curaçao',
    terms: '+18 | T&C APPLY',
    description: '• There MAY be a promotion of €10 free or another promotion on our Discord. Open a ticket to check if the promotion is active.\n\n• 24/7 Live Support (for help with free spins)',
    link: 'https://example.com/lollyspins'
  },
  {
    id: 4,
    name: 'Flagman',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
    bonusTitle: '125FS on signup & 100€ Free Bets',
    minDeposit: '10€',
    bonusValue: '150%',
    freeSpins: 'Up to 125',
    cashback: null,
    code: 'GODMOTA',
    withdrawTime: 'Up to 48h',
    license: 'Curaçao',
    terms: '+18 | T&C APPLY',
    description: '• There MAY be a promotion of €10 free or another promotion on our Discord. Open a ticket to check if the promotion is active.\n\n• 24/7 Live Support (for help with free spins)',
    link: 'https://example.com/flagman'
  },
  {
    id: 5,
    name: 'Lootbox',
    image: 'https://images.unsplash.com/photo-1620421680010-0766ff230392?w=400&h=300&fit=crop',
    bonusTitle: '5% On Every Deposit & VIP Battle',
    minDeposit: '1€',
    bonusValue: '5%',
    freeSpins: null,
    cashback: null,
    code: 'GODMOTA',
    withdrawTime: 'Up to 48h',
    license: 'Curaçao',
    terms: '+18 | T&C APPLY',
    description: '• There MAY be a promotion of €10 free or another promotion on our Discord. Open a ticket to check if the promotion is active.\n\n• 24/7 Live Support (for help with free spins)',
    link: 'https://example.com/lootbox'
  },
  {
    id: 6,
    name: 'Cashpot',
    image: 'https://images.unsplash.com/photo-1571974599782-87624638275e?w=400&h=300&fit=crop',
    bonusTitle: '400% Bonus & 350FS up to €2200',
    minDeposit: '10€',
    bonusValue: '400%',
    freeSpins: 'Up to 350',
    cashback: null,
    code: 'GODCB',
    withdrawTime: 'Up to 48h',
    license: 'Curaçao',
    terms: '+18 | T&C APPLY',
    description: '• There MAY be a promotion of €10 free or another promotion on our Discord. Open a ticket to check if the promotion is active.\n\n• 24/7 Live Support (for help with free spins)',
    link: 'https://example.com/cashpot'
  }
];
